services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: hadi-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: hadi
      POSTGRES_PASSWORD: hadi_password
      POSTGRES_DB: hadi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
